In [1]:
import pandas as pd
import numpy as np
# Step 1:RAW DATA 

data = {
    'Student_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Midhat', 'Mahender', 'Kritika', 'Ajay', 'Shruti', 'Ritik'],
    'Age': [21, 22, 20, 23, 21, 22],
    'Study_Hours': [5, 7, 4, 8, 6, 3],
    'Marks': [72, 85, 65, 91, 78, 59],
    'Department': ['IT', 'CS', 'IT', 'DS', 'CS', 'IT']
}
df = pd.DataFrame(data)
print("raw data")
print(df)
print("\nDATAFRAME INFORMATION")
df.info()
# Step 2: NUMPY - SHAPE, SIZE, DIMENSION
numeric_df = df[
    ['Age', 'Study_Hours', 'Marks']
]

arr = numeric_df.to_numpy()

print("\nNUMPY ARRAY")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)
# Step 3: NUMPY OPERATIONS ON TWO ARRAYS

A = np.array([
    [2, 3],
    [4, 5]
])

B = np.array([
    [6, 7],
    [8, 9]
])

print("\nARRAY A:")
print(A)

print("\nARRAY B:")
print(B)

# Addition
print("\nADDITION")
print(A + B)

# Subtraction
print("\nSUBTRACTION")
print(A - B)

# Multiplication
print("\nMULTIPLICATION")
print(A * B)
# Matrix Multiplication
print("\nMATRIX PRODUCT")
print(A @ B)

# Transpose
print("\nTRANSPOSE OF A")
print(A.T)

print("\nTRANSPOSE OF B")
print(B.T)

# Inverse
print("\nINVERSE OF A")
print(np.linalg.inv(A))

print("\nINVERSE OF B")
print(np.linalg.inv(B))
# Step 4: ONE-HOT ENCODING
print("\nCATEGORICAL DATA")
print(df[['Name', 'Department']])
encoded_df = pd.get_dummies(
    df,
    columns=['Department'],
  dtype=int
)
print("\nOne-Hot Encoded Data:")
print(encoded_df)

raw data
   Student_ID      Name  Age  Study_Hours  Marks Department
0         101    Midhat   21            5     72         IT
1         102  Mahender   22            7     85         CS
2         103   Kritika   20            4     65         IT
3         104      Ajay   23            8     91         DS
4         105    Shruti   21            6     78         CS
5         106     Ritik   22            3     59         IT

DATAFRAME INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Student_ID   6 non-null      int64 
 1   Name         6 non-null      object
 2   Age          6 non-null      int64 
 3   Study_Hours  6 non-null      int64 
 4   Marks        6 non-null      int64 
 5   Department   6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes

NUMPY ARRAY
[[21  5 72]
 [22  7 85]
 [20  4 65]
 [23  8 91]
 [21